# See https://stackoverflow.com/questions/58243255/circleci-testing-with-specific-miniconda-python-and-numpy-versions
version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - py312
      - py311

test-template: &test-template
  docker:
    - image: cimg/base:2021.04
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}

    - run:
        name: install anaconda
        command: |
          cd $HOME
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          chmod +x ~/miniconda.sh && bash ~/miniconda.sh -b -p $HOME/miniconda
          export PATH=$HOME/miniconda/bin:$PATH

    - run:
        name: Install numpy, cython, mdtraj
        command: |
          export PATH="$HOME/miniconda/bin:$PATH"
          conda update  --yes conda
          echo $PYTHON_VERSION
          conda create -f ci/$PYTHON_VERSION.yml -c conda-forge
          source activate calculator
          python --version

    - save_cache:
        paths:
          - ~/miniconda
        key: v1-dependencies-{{ checksum "setup.py" }}

    - run:
        name: Run tests
        command: |
          export PATH=$HOME/miniconda/bin:$PATH
          source activate calculator
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator

    - store_artifacts:
        path: test-reports
        destination: test-reports

jobs:
  py312:
    <<: *test-template

  py311:
    <<: *test-template
